[tool.black]
line-length = 120

[tool.mypy]
exclude = ["^setup.py$"]

[tool.pylint]
disable = [
    "redefined-outer-name",
    "too-many-arguments",
    "too-many-positional-arguments",
]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"
max-line-length = 120
